# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2c98e51d1ba2b2546f9f6dff75b02f3abb61ef3f1fb7ae940b18a00e5490c5acd199a455997cf2a47867ceb2430185d4e13a2fbcabcd22f63ba41341b2f5773

test:
  secret_key_base: 001769e1d1b011d33968fcd74a5760fb0d6272c964ca06f7cb99d6ee0ac9d5b472d0a906eeacb744651baa45a4f3cf82fe0ddd9079d1aa27380f71f02bff1ac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
